Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/04/2026
Var
   // Seção de Declarações das variáveis
   X: Inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   X <- 1
escreval (X)
enquanto (X) < 5 faça
   X <- 1
fimenquanto



Fimalgoritmo