Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/05/2026
Var
// Seção de Declarações das variáveis 
contador, resultado, numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        escreva ("Digite o número para a tabuada:")
        leia (numero)
        
        para contador de 1 ate 10 faca
        resultado <- contador * numero
        escreval (numero, " x", contador," =", resultado)
        fimpara

Fimalgoritmo