Algoritmo "EXERCICIO 4 CELSIUS PARA FARENHEIT"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : PERIMETRO DE UM CIRCULO! (função)
// Autor(a)    : Vinícius Almendanha de Souza
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis
CELSIUS: REAL
FARENHEIT: REAL

Inicio
// CRIE UM PROGRAMA PARA CALCULAR A CIRCUNFERENCIA (PERIMETRO) DE UM CIRCULO

ESCREVAL ("DIGITE O VALOR DO FARENHEIT")


LEIA (FARENHEIT)
CELSIUS<-(FARENHEIT-32)*5/9

ESCREVAL("CELSIUS=",CELSIUS,"C")

Fimalgoritmo