Algoritmo "EXERCICIO 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : PERIMETRO DE UM CIRCULO! (função)
// Autor(a)    : Vinícius Almendanha de Souza
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis
RAIO: REAL
PERIMETRO: REAL

Inicio
// CRIE UM PROGRAMA PARA CALCULAR A CIRCUNFERENCIA (PERIMETRO) DE UM CIRCULO

PI<-3,1416

ESCREVAL ("DIGITE O VALOR DO RAIO")
LEIA (RAIO)
PERIMETRO<-(2*PI*RAIO)

ESCREVAL("PERIMETRO=",PERIMETRO)

Fimalgoritmo