Algoritmo "EXERCICIO 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinícius Almendanha de Souza
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis
A,B,C: INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A<-10
B<-5
C<-A+B
B<-20
A<-5
B<-B-2

ESCREVAL("A=",A)
ESCREVAL("B=",B)
ESCREVAL("C=",C)

Fimalgoritmo