Algoritmo "EXERCICIO 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinícius Almendanha de Souza
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis
A,B,C: INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A<-10
B<-A+3
A<-A+B
B<-B+2
C<-B-2+A

ESCREVAL("A=",A)
ESCREVAL("B=",B)
ESCREVAL("C=",C)

Fimalgoritmo